--DROP DATABASE ProjetoDB12;
GO
CREATE DATABASE ProjetoDB12;
GO
USE ProjetoDB12;
-- caebeçalho inicial de comandos para facilitar a "compilação"

GO

-- criação da tabela PARTIDO
CREATE TABLE partido 
	(
		cod_PARTIDO INTEGER NOT NULL PRIMARY KEY,
		nome_PARTIDO VARCHAR(100) NOT NULL,
		sigla_PARTIDO VARCHAR(8) NOT NULL
	)

GO
-- criação da tabela PREFEITO
CREATE TABLE prefeito
	(
		id_PREFEITO INTEGER NOT NULL PRIMARY KEY,
		emailP_PREFEITO VARCHAR(50) NOT NULL,
		emailS_PREFEITO VARCHAR(50) NOT NULL,
		nome_PREFEITO VARCHAR(128) NOT NULL,
		cod_PARTIDO INTEGER NOT NULL FOREIGN KEY REFERENCES partido(cod_PARTIDO)
	)
	
GO	

-- criação da tabela TRANSFERÊNCIA DE RENDA(transfRenda)
CREATE TABLE transfRenda	
	(
		cod_TRANSFRENDA INTEGER NOT NULL PRIMARY KEY,
		nome_TRANSFRENDA VARCHAR(100) NOT NULL,
		participa_TRANSFRENDA BIT NOT NULL
	)

GO
	

-- criaÇão da tabela TIPOCOFINANCIAMENTO
CREATE TABLE tipoCofinanciamento
	(
		cod_TIPOCOFINANCIAMENTO INTEGER NOT NULL PRIMARY KEY,
		tipo_TIPOCOFINANCIAMENTO VARCHAR(10) NOT NULL,
	)
GO
-- criação da tabela COFINANCIAMENTO
CREATE TABLE cofinanciamento
	(
		id_COFINANCIAMENTO INTEGER NOT NULL PRIMARY KEY,
		especialMediaComplex_COFINANCIAMENTO VARCHAR(50) NOT NULL,
		tipo_COFINANCIAMENTO INTEGER NOT NULL,
		especialAltaComplex_COFINANCIAMENTO VARCHAR(50) NOT NULL,
		diferenca_COFINANCIAMENTO VARCHAR(50),
		cod_TIPOCOFINANCIAMENTO INTEGER NOT NULL FOREIGN KEY REFERENCES tipoCofinanciamento(cod_TIPOCOFINANCIAMENTO) -- relação entre a tabela cofinanciamento e tipo coficnanciamento
	)

GO

-- criação da tabela EXECUTORAS
CREATE TABLE executoras
	(
		id_EXECUTORAS INTEGER NOT NULL PRIMARY KEY,
		nome_EXECUTORAS VARCHAR(100) NOT NULL,
		quantidade_EXECUTORAS INTEGER
	)
	
GO




	

	


	
-- criação da tabela EXECUTORASPRIVADAS
CREATE TABLE executorasPrivadas
	(
		cod_EXECUTORASPRIVADAS INTEGER NOT NULL PRIMARY KEY,
		nome_EXECUTORASPRIVADAS VARCHAR(100) NOT NULL,
	)
	
GO
	
-- criação da tabela EXECUTORASPUBLICAS
CREATE TABLE executorasPublicas
	(
		cod_EXECUTORASPUBLICAS INTEGER NOT NULL PRIMARY KEY,
		nome_EXECUTORASPUBLICAS VARCHAR(100) NOT NULL,
	)
	
GO
	
--criação da tabela ORGAOGESTOR
CREATE TABLE orgaoGestor
	(
		nome_ORGAOGESTOR VARCHAR(100) NOT NULL,
		id_ORGAOGESTOR INTEGER NOT NULL PRIMARY KEY,
		endereco_ORGAOGESTOR VARCHAR(150),
	)
	
GO
	
-- criação da tabela CONSELHOS
CREATE TABLE conselhos
	(
		cod_CONSELHOS INTEGER NOT NULL PRIMARY KEY,
		nome_CONSELHOS VARCHAR(100) NOT NULL,
	)
	
GO
	
-- criação da tabela SECRETARIOMUNICIPAL
CREATE TABLE secretarioMunicipal
	(
		id_SECRETARIOMUNICIPAL INTEGER NOT NULL PRIMARY KEY,
		telefone_SECRETARIOMUNICIPAL VARCHAR(12) NOT NULL,
		emailP_SECRETARIOMUNICIPAL VARCHAR(50) NOT NULL,
		nome_SECRETARIOMUNICIPAL VARCHAR(100) NOT NULL,
		emailS_SECRETARIOMUNICIPAL VARCHAR(100),
		id_ORGAOGESTOR INTEGER NOT NULL FOREIGN KEY REFERENCES orgaoGestor(id_ORGAOGESTOR), -- referencia a entidade ORGAOGESTOR
	)

GO
	

-- criação de CMAS E FMAS
CREATE TABLE cmas
	(
		cod_CMAS INTEGER NOT NULL PRIMARY KEY,
		diretor_CMAS VARCHAR(100) NOT NULL,
		termMandato_CMAS DATE NOT NULL,
	)
	
GO
	
CREATE TABLE fmas
	(
		cod_FMAS INTEGER NOT NULL PRIMARY KEY,
		diretor_FMAS VARCHAR(100) NOT NULL,
		termMandato_FMAS DATE NOT NULL,
	)
	
GO
	

-- criação da tabela PREFEITURA
CREATE TABLE prefeitura
	(
		cod_PREFEITURA INTEGER NOT NULL PRIMARY KEY,
		endereco_PREFEITURA VARCHAR NOT NULL,
		porte_PREFEITURA VARCHAR NOT NULL, -- que porra é essa?
		tipoGestao_PREFEITURA VARCHAR NOT NULL,
		principaisProblemasSociais_PREFEITURA TEXT,
		telefone_PREFEITURA VARCHAR NOT NULL,
		numeroHabitantes_PREFEITURA INTEGER NOT NULL,
		municipio_PREFEITURA VARCHAR NOT NULL,
		id_PREFEITO INTEGER NOT NULL FOREIGN KEY REFERENCES prefeito(id_PREFEITO), -- relação com a tabela PREFEITO
		cod_TRANSFRENDA INTEGER NOT NULL FOREIGN KEY REFERENCES transfRenda(cod_TRANSFRENDA), -- relação com a tabela TRANSFRENDA
		id_COFINANCIAMENTO INTEGER NOT NULL FOREIGN KEY REFERENCES cofinanciamento(id_COFINANCIAMENTO), -- relação com a tabela COFINANCIAMENTO
		id_EXECUTORAS INTEGER NOT NULL FOREIGN KEY REFERENCES executoras(id_EXECUTORAS), -- relação com a tabela EXECUTORAS
		cod_EXECUTORASPRIVADAS INTEGER NOT NULL FOREIGN KEY REFERENCES executorasPrivadas(cod_EXECUTORASPRIVADAS), -- relação com a entidade EXECUTORASPRIVADAS
		cod_EXECUTORASPUBLICAS INTEGER NOT NULL FOREIGN KEY REFERENCES executorasPublicas(cod_EXECUTORASPUBLICAS), -- relação com a entidade EXECUTORASPUBLICAS
		cod_CONSELHOS INTEGER NOT NULL FOREIGN KEY REFERENCES conselhos(cod_CONSELHOS), -- relação com a entidade CONSELHOS
		id_SECRETARIOMUNICIPAL INTEGER NOT NULL FOREIGN KEY REFERENCES secretarioMunicipal(id_SECRETARIOMUNICIPAL), -- relação com a entidade SECRETARIOMUNICIPAL		
	)

GO
