--DROP DATABASE ProjetoDB1;
--GO
CREATE DATABASE ProjetoDB1;
GO
USE ProjetoDB1;
-- caebeçalho inicial de comandos para facilitar a "compilação"

GO
-- criação de CMAS E FMAS
CREATE TABLE cmas
	(
		cod_CMAS INTEGER NOT NULL PRIMARY KEY,
		diretor_CMAS VARCHAR(100) NOT NULL,
		termMandato_CMAS DATE NOT NULL,
	)
	
GO
	
CREATE TABLE fmas
	(
		cod_FMAS INTEGER NOT NULL PRIMARY KEY,
		diretor_FMAS VARCHAR(100) NOT NULL,
		termMandato_FMAS DATE,
	)
	
GO

-- criação da tabela PARTIDO
CREATE TABLE partido 
	(
		cod_PARTIDO INTEGER NOT NULL PRIMARY KEY,
		nome_PARTIDO VARCHAR(100) NOT NULL,
		sigla_PARTIDO VARCHAR(8) NOT NULL
	)

GO
-- criação da tabela PREFEITO
CREATE TABLE prefeito
	(
		id_PREFEITO INTEGER NOT NULL PRIMARY KEY,
		emailP_PREFEITO VARCHAR(50) NOT NULL,
		emailS_PREFEITO VARCHAR(50) NOT NULL,
		nome_PREFEITO VARCHAR(128) NOT NULL,
		cod_PARTIDO INTEGER NOT NULL FOREIGN KEY REFERENCES partido(cod_PARTIDO)
	)
	
GO	


	

-- criaÇão da tabela TIPOCOFINANCIAMENTO
CREATE TABLE tipoCofinanciamento
	(
		cod_TIPOCOFINANCIAMENTO INTEGER NOT NULL PRIMARY KEY,
		tipo_TIPOCOFINANCIAMENTO VARCHAR(10) NOT NULL,
	)
GO


--criação da tabela TIPOEXECUTORA

CREATE TABLE tipoExecutora
	(
		cod_TIPOEXECUTORA INTEGER NOT NULL PRIMARY KEY,
		tipo_TIPOEXECUTORA VARCHAR(8) NOT NULL,
	)



	
-- criação da tabela EXECUTORASPRIVADAS
/*CREATE TABLE executorasPrivadas
	(
		cod_EXECUTORASPRIVADAS INTEGER NOT NULL PRIMARY KEY,
		nome_EXECUTORASPRIVADAS VARCHAR(100) NOT NULL,
	)
	
GO
	
-- criação da tabela EXECUTORASPUBLICAS
CREATE TABLE executorasPublicas
	(
		cod_EXECUTORASPUBLICAS INTEGER NOT NULL PRIMARY KEY,
		nome_EXECUTORASPUBLICAS VARCHAR(100) NOT NULL,
	)
*/	
GO

	
--criação da tabela ORGAOGESTOR
CREATE TABLE orgaoGestor
	(
		nome_ORGAOGESTOR VARCHAR(100) NOT NULL,
		id_ORGAOGESTOR INTEGER NOT NULL PRIMARY KEY,
		endereco_ORGAOGESTOR VARCHAR(150),
		cod_FMAS INTEGER FOREIGN KEY REFERENCES fmas(cod_FMAS),
		cod_CMAS INTEGER FOREIGN KEY REFERENCES cmas(cod_CMAS)
	)
	
GO
	
-- criação da tabela SECRETARIOMUNICIPAL
CREATE TABLE secretarioMunicipal
	(
		id_SECRETARIOMUNICIPAL INTEGER NOT NULL PRIMARY KEY,
		telefone_SECRETARIOMUNICIPAL VARCHAR(12) NOT NULL,
		emailP_SECRETARIOMUNICIPAL VARCHAR(50) NOT NULL,
		nome_SECRETARIOMUNICIPAL VARCHAR(100) NOT NULL,
		emailS_SECRETARIOMUNICIPAL VARCHAR(100),
		id_ORGAOGESTOR INTEGER NOT NULL FOREIGN KEY REFERENCES orgaoGestor(id_ORGAOGESTOR) -- referência a entidade ORGAOGESTOR
	)

GO



-- criação da tabela PREFEITURA
CREATE TABLE prefeitura
	(
		cod_PREFEITURA INTEGER NOT NULL PRIMARY KEY,
		endereco_PREFEITURA VARCHAR (100) NOT NULL,
		--porte_PREFEITURA VARCHAR NOT NULL, -- 
		tipoGestao_PREFEITURA VARCHAR (6) NOT NULL,
		principaisProblemasSociais_PREFEITURA TEXT,
		telefone_PREFEITURA VARCHAR (12) NOT NULL,
		numeroHabitantes_PREFEITURA INTEGER NOT NULL,
		municipio_PREFEITURA VARCHAR (20) NOT NULL,
		id_PREFEITO INTEGER NOT NULL FOREIGN KEY REFERENCES prefeito(id_PREFEITO), -- relação com a tabela PREFEITO
		--cod_TRANSFRENDA INTEGER NOT NULL FOREIGN KEY REFERENCES transfRenda(cod_TRANSFRENDA), -- relação com a tabela TRANSFRENDA
		--id_COFINANCIAMENTO INTEGER NOT NULL FOREIGN KEY REFERENCES cofinanciamento(id_COFINANCIAMENTO), -- relação com a tabela COFINANCIAMENTO
		--id_EXECUTORA INTEGER NOT NULL FOREIGN KEY REFERENCES executora(id_EXECUTORA), -- relação com a tabela EXECUTORAS
		--cod_EXECUTORASPRIVADAS INTEGER NOT NULL FOREIGN KEY REFERENCES executorasPrivadas(cod_EXECUTORASPRIVADAS), -- relação com a entidade EXECUTORASPRIVADAS
		--cod_EXECUTORASPUBLICAS INTEGER NOT NULL FOREIGN KEY REFERENCES executorasPublicas(cod_EXECUTORASPUBLICAS), -- relação com a entidade EXECUTORASPUBLICAS
		--cod_CONSELHOS INTEGER NOT NULL FOREIGN KEY REFERENCES conselhos(cod_CONSELHOS), -- relação com a entidade CONSELHOS
		id_SECRETARIOMUNICIPAL INTEGER NOT NULL FOREIGN KEY REFERENCES secretarioMunicipal(id_SECRETARIOMUNICIPAL), -- relação com a entidade SECRETARIOMUNICIPAL		
	)

GO
-- criação da tabela COFINANCIAMENTO
CREATE TABLE cofinanciamento
	(
		id_COFINANCIAMENTO INTEGER NOT NULL PRIMARY KEY,
		niveldecomplexidade VARCHAR(50) NOT NULL,
		cod_TIPOCOFINANCIAMENTO INTEGER NOT NULL FOREIGN KEY REFERENCES tipoCofinanciamento(cod_TIPOCOFINANCIAMENTO), -- relação entre a tabela cofinanciamento e tipo coficnanciamento
		redePublica VARCHAR(50),
		redePrivada VARCHAR(50),
		cod_PREFEITURA INTEGER NOT NULL FOREIGN KEY REFERENCES prefeitura (cod_PREFEITURA),
		
	)

GO
-- criação da tabela EXECUTORAS
CREATE TABLE executora
	(
		id_EXECUTORA INTEGER NOT NULL PRIMARY KEY,
		nome_EXECUTORA VARCHAR(100) NOT NULL,
		quantidade_EXECUTORA INTEGER,
		cod_PREFEITURA INTEGER NOT NULL FOREIGN KEY REFERENCES prefeitura (cod_PREFEITURA),
		cod_TIPOEXECUTORA INTEGER FOREIGN KEY REFERENCES tipoExecutora(cod_TIPOEXECUTORA)
	)
	
GO

-- criação da tabela TIPO TRANSFERÊNCIA DE RENDA(tipoTransfRenda)
CREATE TABLE tipoTransfRenda
	(
		id_tipotranfRenda INTEGER NOT NULL PRIMARY KEY,
		nome_TRANSFRENDA VARCHAR(100) NOT NULL,);
-- criação da tabela TRANSFERÊNCIA DE RENDA(transfRenda)GO

CREATE TABLE transfRenda	
	(
		cod_TRANSFRENDA INTEGER NOT NULL PRIMARY KEY,
		id_tipotransfRenda INTEGER NOT NULL FOREIGN KEY REFERENCES tipoTransfRenda (id_tipotranfRenda),
		cod_PREFEITURA INTEGER NOT NULL FOREIGN KEY REFERENCES prefeitura (cod_PREFEITURA),
		participa_TRANSFRENDA BIT NOT NULL

	)

GO
-- criação da tabela CONSELHOS
CREATE TABLE conselhos
	(
		cod_CONSELHOS INTEGER NOT NULL PRIMARY KEY,
		cod_PREFEITURA INTEGER NOT NULL FOREIGN KEY REFERENCES prefeitura (cod_PREFEITURA),
		nome_CONSELHOS VARCHAR(100) NOT NULL,
	)
	
GO